dag_id: "uni_flores"

task1_id: "uf"
kwargs1: {'path_query_UF':'/home/jmsiro/airflow/dags/src/query_UF.sql', 
'path_PC':'/home/jmsiro/airflow/dags/data_base/codigos_postales.csv',
'path_csv':'/home/jmsiro/airflow/dags/data_base', 
'filename':'UF'}

task2_id: 'uf'
kwargs2: {'path_txt':'/home/jmsiro/airflow/dags/data_processed', 
'filename':'UF'}

task3_id: 'uf'
kwargs3: {'bucket_name': config('BUCKET_NAME'),
'aws_access_key_id': config('PUBLIC_KEY'), 
'aws_secret_access_key': config('SECRET_KEY'),
'region_name': config('REGION')}